import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdir, rm } from "node:fs/promises";
import { join } from "node:path";
import type { Logger } from "../domain/logger.js";

const exec = promisify(execFile);

export class GitWorktreeManager {
  constructor(
    private readonly projectRoot: string,
    private readonly logger: Logger,
  ) {}

  /**
   * Ensures the .worktrees directory exists and prunes stale Git worktrees.
   */
  async initialize(worktreesDir: string): Promise<void> {
    await mkdir(worktreesDir, { recursive: true });
    try {
      // Execute git worktree prune securely (no shell interpolation).
      await exec("git", ["worktree", "prune"], { cwd: this.projectRoot });
    } catch (error) {
      this.logger.warn("workspace.git_prune_failed", { error: String(error) });
    }
  }

  /**
   * Resolves a reference (e.g. HEAD, branch, or SHA) to its full SHA to ensure immutable base.
   */
  async resolveBaseRef(ref: string = "HEAD"): Promise<string> {
    try {
      const { stdout } = await exec("git", ["rev-parse", ref], { cwd: this.projectRoot });
      return stdout.trim();
    } catch (error) {
      this.logger.error("workspace.git_resolve_ref_failed", { ref, error: String(error) });
      throw new Error(`Failed to resolve base ref '${ref}'`);
    }
  }

  /**
   * Creates a Git worktree.
   * @param targetPath Absolute path where the worktree should be created.
   * @param branchName Unique branch name generated by the service.
   * @param baseRef The verified SHA or base reference.
   */
  async createWorktree(targetPath: string, branchName: string, baseRef: string): Promise<void> {
    try {
      // Use execFile with explicit array to prevent shell injection.
      await exec("git", ["worktree", "add", "-b", branchName, targetPath, baseRef], {
        cwd: this.projectRoot,
      });
      this.logger.debug("workspace.git_worktree_created", { dir: targetPath, branch: branchName, base: baseRef });
    } catch (error) {
      this.logger.error("workspace.git_worktree_create_failed", { targetPath, error: String(error) });
      throw new Error(`Failed to create git worktree at ${targetPath}: ${String(error)}`);
    }
  }

  /**
   * Removes a Git worktree forcefully and attempts to delete its branch.
   */
  async removeWorktree(targetPath: string, branchName?: string): Promise<void> {
    let removeFailed = false;
    try {
      await exec("git", ["worktree", "remove", "--force", targetPath], { cwd: this.projectRoot });
      this.logger.debug("workspace.git_worktree_removed", { dir: targetPath });
    } catch (error) {
      this.logger.warn("workspace.git_worktree_remove_failed", { dir: targetPath, error: String(error) });
      removeFailed = true;
    }

    // If worktree remove failed, fallback to rm -rf so disk space doesn't leak.
    if (removeFailed) {
      try {
        await rm(targetPath, { recursive: true, force: true });
        // After forceful directory removal, prune git worktrees so git forgets about it.
        await exec("git", ["worktree", "prune"], { cwd: this.projectRoot });
      } catch (rmError) {
        this.logger.warn("workspace.git_worktree_rm_failed", { dir: targetPath, error: String(rmError) });
      }
    }

    if (branchName) {
      try {
        await exec("git", ["branch", "-D", branchName], { cwd: this.projectRoot });
        this.logger.debug("workspace.git_branch_deleted", { branch: branchName });
      } catch (branchError) {
        this.logger.warn("workspace.git_branch_delete_failed", { branch: branchName, error: String(branchError) });
      }
    }
  }
}
